### ISSUE TITLE
[Enhancement] Add Informational Banner to Pages that Cannot be Updated

### ISSUE THREAD

**Issue by MalHus** [WISE-UofT/wise-main#10]
Add a banner under the navigation bar for each page that contains outdated content that can only be updated in September 2024.

**Comment by helenaglow** [comment]
![MacBook Air - 1](https://github.com/user-attachments/assets/e302df35-8b44-4861-9bf1-c9f39fc926b2)

Something like this @MalHus

**Comment by MalHus** [comment]
Thank you Helena! I have made the change, the icon is not the same however. Is there a specific library that is preferred? I have used [Bootstrap Icons](https://icons.getbootstrap.com/icons/info-circle/) in this PR.

**Comment by MalHus** [comment]
> Thank you Helena! I have made the change, the icon is not the same however. Is there a specific library that is preferred? I have used [Bootstrap Icons](https://icons.getbootstrap.com/icons/info-circle/) in this PR.

Addressed here: https://github.com/WISE-UofT/wise-main/pull/13
