### ISSUE TITLE
[Improvement] Fix Uneven Picture Distribution in Conference Page

### ISSUE THREAD

**Issue by MalHus** [WISE-UofT/wise-main#20]
Readjust pictures to evenly fit the page in the Conference > Our 2024 National Conference page by moving some pictures to the 4rth, currently empty, column.
![image](https://github.com/user-attachments/assets/be581663-c11e-4de0-8bef-3f65ded2fefe)

**Comment by MalHus** [comment]
With the changes:
![image](https://github.com/user-attachments/assets/1555bb79-601f-42b6-aa5f-96449fa96112)

However, I think it looked better originally: http://127.0.0.1:5501/conference.html

Any suggestions @helenaglow?

**Comment by helenaglow** [comment]
try centering it @MalHus

**Comment by helenaglow** [comment]
Or make it a carousel
