### ISSUE TITLE
[Bug] Improve Content Alignment and Spacing in "Opportunities"

### ISSUE THREAD

**Issue by MalHus** [WISE-UofT/wise-main#21]
- Improve the uneven padding around the collapsible content (in gray) for each opportunity
- Align the grey content box with its title's box in purple 
![image](https://github.com/user-attachments/assets/065045bb-162c-413f-9538-82bf01690688)

- Align the “Last Updated” text with purple boxes above
![image](https://github.com/user-attachments/assets/3254ae83-c2dc-4cf8-81ec-ce29f7cfc574)

**Comment by helenaglow** [comment]
So true
