### ISSUE TITLE
[Bug] Update Button Color and Sticky Button in "Stories of Wise"

### ISSUE THREAD

**Issue by MalHus** [WISE-UofT/wise-main#22]
- Update color of each button to meet the WISE [color scheme](https://docs.google.com/document/d/1OupiHNsNTt9gvzeo_vDEV8PHHdUedUTctSxef4a_TCc/edit).
- Adding padding around the buttons to prevent hiding the content

![image](https://github.com/user-attachments/assets/3ea21b26-c172-4869-8842-8e1d61838d46)

- Delete the sub heading once "Read more" is clicked.
![image](https://github.com/user-attachments/assets/6d2cc32d-f8f4-4d90-8dbb-1b6e4e5a97bc)

**Comment by helenaglow** [comment]
I think overall this page needs to be re styled but I think the buttons are a good start

**Comment by MalHus** [comment]
> I think overall this page needs to be re styled but I think the buttons are a good start

I see this is an existing improvement in the [marketing vision](https://docs.google.com/document/d/1OupiHNsNTt9gvzeo_vDEV8PHHdUedUTctSxef4a_TCc/edit).
