### ISSUE TITLE
[Bug] Fix Nav Bar Dropdown Menu Glitches

### ISSUE THREAD

**Issue by MalHus** [WISE-UofT/wise-main#9]
Redesign the navigation bar, ensuring the **problem~~s~~** below are addressed. 

The current navigation bar has the following issues:
- _Dropdown Menu Glitches_: Adjacent dropdown items overlap and glitch when hovered.
- ~~_Hamburger Menu Position_: The hamburger menu appears on the left side when the page is resized (as discussed with Helena).~~

https://github.com/user-attachments/assets/4b39f2c9-1350-43e1-a92e-0a41456f38b9

https://github.com/user-attachments/assets/4d518bce-81b4-43d3-850d-af9340493ba8

Suggestions and guidance on the drop down navigation bar designs from VP of marketing would be appreciated 💜!

**Comment by helenaglow** [comment]
I think for the hamburger navigation dropdown we can currently leave it how it is! It is not a priority right now

**Comment by MalHus** [comment]
Alright, perhaps we should redefine the scope of this PR. Should it be only fixing the **dropdown menu glitches**?

**Comment by helenaglow** [comment]
Yes!
